# Makefile for diff

COMPONENT ?= diff
INSTAPP = ${INSTDIR}${SEP}!Diff

LIBS = ${CLXLIB}
INSTAPP_FILES = !Boot !Help !Run !Sprites [!Sprites11] !Sprites22 Desc Messages Templates
INSTAPP_VERSION = Desc

include CApp

# Dynamic dependencies:
